add_newline = true

format = """
$python\
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$git_metrics\
$line_break\
$character"""

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[python]
format = '(\($virtualenv\) )'

[directory]
style = "blue"
truncation_length = 3
truncate_to_repo = false
