add_newline = true

format = """
$status\
$cmd_duration\
$line_break\
$sudo\
$shell\
$nix_shell\
$python\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_status\
$git_metrics\
$line_break\
$character"""

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[python]
format = '(\($virtualenv\) )'

[directory]
style = "blue"
truncation_length = 3
truncate_to_repo = false

[status]
format = '[$status]($style) '
# success symbol must be non-empty for module to show when no error occurs
success_symbol = 'Y'
map_symbol = true
disabled = false

[sudo]
disabled = false
format = '$symbol'

[cmd_duration]
format = '\(after [$duration]($style)\) '

[nix_shell]
symbol = '❆ '
format = '[$symbol]($style)'
disabled = false

[shell]
zsh_indicator = ''
bash_indicator = 'bash '
format = '$indicator'
disabled = false
